// This file is auto generated by icy-vector
#include "icydb.h"
typedef struct _array_table{
  char ** column_names;
  char ** column_types;
  size_t * count;
  size_t * capacity;
  size_t * free_index_count;
  const size_t column_count;
  icy_mem * free_indexes;
  icy_mem * header;
  const size_t column_sizes[1];
  
  u32 * data;
  icy_mem * data_area;
}array_table;

// a vector index.
typedef struct{
  size_t index;
}array_table_index;

typedef struct{
  size_t index;
  size_t count;
}array_table_indexes;

array_table * array_table_create(const char * optional_name);
array_table_index array_table_alloc(array_table * table);
array_table_indexes array_table_alloc_sequence(array_table * table, size_t count);
void array_table_remove(array_table * table, array_table_index index);
void array_table_remove_sequence(array_table * table, array_table_indexes * indexes);
void array_table_clear(array_table * table);
void array_table_optimize(array_table * table);
void array_table_destroy(array_table ** table);
