// This file is auto generated by icy-table.
#include "icydb.h"
typedef struct _doubles{
  char ** column_names;
  char ** column_types;
  size_t count;
  const bool is_multi_table;
  const int column_count;
  int (*cmp) (const object_id * k1, const object_id * k2);
  const size_t sizes[2];

  object_id * key;
  double * value;
  icy_mem * key_area;
  icy_mem * value_area;
}doubles;

doubles * doubles_create(const char * optional_name);
void doubles_set(doubles * table, object_id key, double value);
void doubles_insert(doubles * table, object_id * key, double * value, size_t count);
void doubles_lookup(doubles * table, object_id * keys, size_t * out_indexes, size_t count);
void doubles_remove(doubles * table, object_id * keys, size_t key_count);
void doubles_clear(doubles * table);
void doubles_unset(doubles * table, object_id key);
bool doubles_try_get(doubles * table, object_id * key, double * value);
void doubles_print(doubles * table);
size_t doubles_iter(doubles * table, object_id * keys, size_t keycnt, object_id * optional_keys_out, size_t * indexes, size_t cnt, size_t * iterator);
