// This file is auto generated by icy-vector
#include "icydb.h"
typedef struct _icy_types{
  char ** column_names;
  char ** column_types;
  size_t * count;
  size_t * capacity;
  size_t * free_index_count;
  const size_t column_count;
  icy_mem * free_indexes;
  icy_mem * header;
  const size_t column_sizes[1];
  
  icy_type * type;
  icy_mem * type_area;
}icy_types;

// a vector index.
typedef struct{
  size_t index;
}icy_types_index;

typedef struct{
  size_t index;
  size_t count;
}icy_types_indexes;

icy_types * icy_types_create(const char * optional_name);
icy_types_index icy_types_alloc(icy_types * table);
icy_types_indexes icy_types_alloc_sequence(icy_types * table, size_t count);
void icy_types_remove(icy_types * table, icy_types_index index);
void icy_types_remove_sequence(icy_types * table, icy_types_indexes * indexes);
void icy_types_clear(icy_types * table);
void icy_types_optimize(icy_types * table);
void icy_types_destroy(icy_types ** table);
