// This file is auto generated by icy-table.
#include "icydb.h"
typedef struct _id_to_u64{
  char ** column_names;
  char ** column_types;
  size_t count;
  const bool is_multi_table;
  const int column_count;
  int (*cmp) (const object_id * k1, const object_id * k2);
  const size_t sizes[2];

  object_id * key;
  u64 * value;
  icy_mem * key_area;
  icy_mem * value_area;
}id_to_u64;

id_to_u64 * id_to_u64_create(const char * optional_name);
void id_to_u64_set(id_to_u64 * table, object_id key, u64 value);
void id_to_u64_insert(id_to_u64 * table, object_id * key, u64 * value, size_t count);
void id_to_u64_lookup(id_to_u64 * table, object_id * keys, size_t * out_indexes, size_t count);
void id_to_u64_remove(id_to_u64 * table, object_id * keys, size_t key_count);
void id_to_u64_clear(id_to_u64 * table);
void id_to_u64_unset(id_to_u64 * table, object_id key);
bool id_to_u64_try_get(id_to_u64 * table, object_id * key, u64 * value);
void id_to_u64_print(id_to_u64 * table);
size_t id_to_u64_iter(id_to_u64 * table, object_id * keys, size_t keycnt, object_id * optional_keys_out, size_t * indexes, size_t cnt, size_t * iterator);
